name = "vless"
main = "_worker.js"
compatibility_date = "2023-05-26"
[[routes]]
pattern = "*.bmkg.xyz/*"
custom_domain = true

[vars]
PROXYIP = "35.219.15.90"
UUID = "8f4e4a98-0d82-4f4a-a74d-9b547e737594"
